/* Configuration for clic generated by Alire */
#ifndef CLIC_CONFIG_H
#define CLIC_CONFIG_H

#define CRATE_VERSION "0.3.0"
#define CRATE_NAME "clic"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
